### ISSUE TITLE
libv8 (3.16.14.9)

### ISSUE THREAD

**Issue by ele638** [radigin/base_app_m#1]
Пишет ошибку при bundle install:

> Your bundle is locked to libv8 (3.16.14.9), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the
> author of libv8 (3.16.14.9) has removed it. You'll need to update your bundle to a different version of libv8 (3.16.14.9) that hasn't been removed in order to install.

При bundle update && bundle install падает при запуске rails s c ошибкой stack level too deep.

**Comment by Ennea-Fate** [comment]
Как вариант попробовать разлочить версию гема в Gemfile.lock ? 
Падает с stack level too deep потому что у тебя скорее всего rails 4.2.1 (что очевидно указанно в Гемфайле), а ruby у тебя v2.4, там изменили целочисленные типы данных. Либо использовать rails 4.2.1 и ruby 2.3.3 либо использовать rails 5.* + ruby 2.4.Lifehack: Если указать хотя бы базовый набор информации о среде в которой ты пытаешься работать, то коммунити подсказывает гораздо охотнее.

**Comment by radigin** [comment]
Проект без проблем работает в RoR 4.2.7. Можно просто поменять версию в Gemfile. Затем удалите Gemfile.lock и выполните bundle. Это может помочь. А в принципе, как писал автор выше - надо бы указать, что за версия ruby у Вас.

**Comment by ele638** [comment]
Ruby стоит версии 2.0.0 нативная в OSX, 2.2.3 и 2.4.0 через rbenv. Свою ошибку понял, переключился на 2.2.3, поставил 4 рельсы. Запустилось. Всем спасибо. И к слову, Gemfile.lock не удалял, с ним запустилось.

**Comment by radigin** [comment]
Скорее всего Gemfile.lock был уже обновлен, а не из исходного проекта. В исходном проекте очень старая libv8 и на нормальной системе её просто не должно находиться.

**Comment by ele638** [comment]
@radigin, а почему нельзя было обновить все гемы на проекте? И почему никто из администраторов на университетских компьютерах не хочет/не может обновить гемлист?

**Comment by radigin** [comment]
Данный проект написан под те гемы, которые стоят на локалках, чтобы можно было на них его запустить. А вторая часть вашего  вопроса не ко мне...
